require 'custom.set'
require 'custom.statusline'
vim.cmd.packadd 'nvim.undotree'
require 'custom.pack'
require 'custom.remap'
require 'custom.autocmd'
require 'custom.lsp'
require 'custom.treesitter'
